DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  title TEXT NOT NULL,
  cover_image TEXT,
  rating INT,
  price TEXT NOT NULL,
  in_stock BOOLEAN NOT NULL
);
