DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  cover_image TEXT,
  rating INT,
  price TEXT NOT NULL,
  in_stock BOOLEAN NOT NULL
);
